default: &default
  adapter: mysql2
  encoding: utf8
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: kokushi_development
  host: localhost

test:
  <<: *default
  database: kokushi_test
  host: localhost

production:
  <<: *default
  database: kokushi_production
  username: kokushi
  password: <%= ENV['KOKUSHI_DATABASE_PASSWORD'] %>
